# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-28 09:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='district',
            old_name='district_county',
            new_name='district_municipality',
        ),
    ]
