# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-28 09:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20170528_0553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='district_municipality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Municipality'),
        ),
    ]
