# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 17:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20170528_0559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='district',
            name='district_municipality',
        ),
        migrations.AddField(
            model_name='municipality',
            name='municipality_district',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='webapp.District'),
            preserve_default=False,
        ),
    ]
