# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 20:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_auto_20170601_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='district_millage',
            field=models.DecimalField(decimal_places=4, max_digits=7),
        ),
        migrations.AlterField(
            model_name='municipality',
            name='municipality_millage',
            field=models.DecimalField(decimal_places=4, max_digits=6),
        ),
    ]
